name: udemy
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello Wrold!"
      - name: print goodbye
        run: echo "Good Bye"
